- hosts: remote
  become: yes
  vars:
    ssh_port: 23456
  roles:
    - { role: sshd, sshd_ssh_port: "{{ ssh_port }}" }
    - { role: iptables, iptables_ssh_port: "{{ ssh_port }}" }
    - { role: pull-git }
