version: "2"
services:
  nginx:
    image: nginx:1.15.6
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
