- name: Flush iptables
  iptables:
    flush: true

- name: iptables established
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: iptables INPUT
  iptables:
    chain: INPUT
    policy: DROP

- name: iptables OUTPUT
  iptables:
    chain: OUTPUT
    policy: ACCEPT
#- name: iptables drop none
#  iptables:
#    chain: INPUT
#    protocol: tcp
#    tcp_flags: ALL=NON
#    jump: DROP

#- name: iptables drop stealth
#  iptables:
#    chain: INPUT
#    protocol: tcp
#    tcp_flags: ALL=ALL
#    jump: DROP
#  become: yes
#- name: iptables accept local
#  iptables:
#    chain: INPUT
#    in_interface: lo
#    jump: ACCEPT
#  become: yes
#- name: iptables accept ping
#  iptables:
#    chain: INPUT
#    protocol: icmp
#    jump: ACCEPT
#  become: yes
